import React from 'react'

export default function VideInterCom_4_2_2_1() {
  return (
    <div>
    <div className="home_div">
      <div className="home_div2">
        <div className="button_div">
          <a

           href={"http://ftp.hikvision.ru/01.%20Firmware/01.%20Hikvision/05.%20Video%20Intercom/008.%20First%20Gen%20intercom%20devices.%20OLD/2.%20Old%20firmware/V1.5.0/Door%20Station%28D%20series%29/Read%20me.txt"}
            className="button_div2"
          >
            <h5>Read me.txt</h5>
          </a>
          <a

           href={"http://ftp.hikvision.ru/01.%20Firmware/01.%20Hikvision/05.%20Video%20Intercom/008.%20First%20Gen%20intercom%20devices.%20OLD/2.%20Old%20firmware/V1.5.0/Door%20Station%28D%20series%29/VIS_04_H2_OUTDOOR_EN_STD_V1.5.0_180623.zip"}
            className="button_div2"
          >
            <h5>VIS_04_H2_OUTDOOR_EN_STD_V1.5.0_180623.zip</h5>
          </a>
          <a

           href={"http://ftp.hikvision.ru/01.%20Firmware/01.%20Hikvision/05.%20Video%20Intercom/008.%20First%20Gen%20intercom%20devices.%20OLD/2.%20Old%20firmware/V1.5.0/Door%20Station%28D%20series%29/VIS_04_H5_OUTDOOR_EN_STD_V1.5.0_180613.zip"}
            className="button_div2"
          >
            <h5>VIS_04_H5_OUTDOOR_EN_STD_V1.5.0_180613.zip </h5>
          </a>
        </div>
      </div>
    </div>
  </div>
  )
}
